In [1]:
import numpy as np

a = np.random.randint(1,4,4).reshape(2,2)
b = np.random.randint(1,4,4).reshape(2,2)
print(a)
print(b)

[[2 1]
 [3 3]]
[[2 2]
 [3 3]]


In [2]:
a = np.random.randint(1,1000,1000000)
a.mean()

499.700506

In [3]:
a1 = np.random.choice(a,100)
a1
a1.mean()
# a1.standdeviation

522.65

In [4]:
a2 = np.random.choice(a,1000)
a2
a2.mean()

509.636

In [5]:
a3 = np.random.choice(a,10000)
a3
a3.mean()

497.1602

In [6]:
a = np.random.randint(1,20,20)
a.mean()

10.85

In [7]:

print(a)
def custom_mean(a) :
    k= np.sum(a)
    j = len(a)
    return(k/j)
custom_mean(a)

[14  5  2 14 17  8 16 18  4 18  1 14 14 10  9 13  8  2 11 19]


10.85

In [8]:
# a1 = np.sort(a ,inplace= True)
# a1
# (custom_mean(a[math.floor((len(a)-1)/2):math.ceil((len(a)-1)/2)+1]))

# def median:
# #     for i in range(len(a1)):
# #         if len(a1)%2 == 0
#         return(a1[floor(len(a1)+1/2)])

In [9]:
import statistics
statistics.median(a)



12.0

In [10]:

import math
a1 = np.sort(a)
print(a1)
print(math.floor((len(a1))/2))
print(math.ceil((len(a1))/2))
a3=a1[math.floor((len(a1)+1)/2)-1:math.ceil((len(a1)+1)/2)]
print(a3)
a2 =custom_mean(a3)
print(a2)

[ 1  2  2  4  5  8  8  9 10 11 13 14 14 14 14 16 17 18 18 19]
10
10
[11 13]
12.0


In [11]:
r = [1,2,2,3,4,5,5]
s = set(r)
print(s)
t= [1,2,2,3]
print(len(s)+sum(t))

{1, 2, 3, 4, 5}
13


In [12]:
# dir(math)