In [9]:
import numpy as np

a = np.random.randint(1,4,4).reshape(2,2)
b = np.random.randint(1,4,4).reshape(2,2)
print(a)
print(b)

[[2 2]
 [1 1]]
[[1 2]
 [3 3]]


In [15]:
# %%timeit
print(a@b) #CRoss product

[[ 8 10]
 [ 4  5]]


In [11]:
a.dot(b)#CRoss product this is the fastest way to calculate cross product

array([[ 8, 10],
       [ 4,  5]])

In [12]:
a*b #eliment wise metrix multiplication

array([[2, 4],
       [3, 3]])

In [16]:
a.dot(b)

array([[ 8, 10],
       [ 4,  5]])

In [17]:
b.dot(a)

array([[4, 4],
       [9, 9]])