In [1]:
import numpy as np

s = np.random.randint(1,125,125).reshape(5,5,5)
print(s)

[[[ 87  23  92  96 109]
  [ 86  48 120  37  39]
  [ 26  90  13  66  20]
  [118 106  72  24  14]
  [116  82 118  53  85]]

 [[  6  51  61 113  66]
  [ 10  46  16  89  41]
  [ 68  35  42   5  54]
  [ 42  27  65  17  89]
  [ 59 123 108   7  87]]

 [[ 42 101  40 123  92]
  [ 11  98  94 109  67]
  [ 58  19  80  60  95]
  [115  72  53  32  57]
  [ 74  36  22 114  96]]

 [[ 53 106  88  28  67]
  [ 66  58  95  18  37]
  [ 35  19 103  90 101]
  [ 95  80   5  42  24]
  [ 61  37  26  29  36]]

 [[ 54  90  14  68  69]
  [ 53  71   2  54  90]
  [ 83  36  71  94  58]
  [ 73  47  31   1  68]
  [ 78  36  63  73   8]]]


In [2]:
a = np.random.randint(0,25,25).reshape(5,5)

np.triu(a)
np.tril(a)

array([[ 9,  0,  0,  0,  0],
       [19, 14,  0,  0,  0],
       [23, 23, 11,  0,  0],
       [10, 10,  8, 18,  0],
       [11,  3, 15, 19,  2]])

In [3]:
M1 = np.random.randint(1,16,16).reshape(4,4)
MT1 = M1.T
comparison = M1 == MT1

if comparison.all() == True:
    print("Value matched")
else:
    print("Not Matched")

Not Matched


In [9]:
a = np.random.randint(1,6,6).reshape(2,3)
b = np.random.randint(1,6,6).reshape(2,3)
c = a*b 
print(a)
print()
print(b)
print()
print(c)

[[5 2 1]
 [1 1 1]]

[[3 2 1]
 [2 2 4]]

[[15  4  1]
 [ 2  2  4]]


In [ ]:
s = '2'

In [ ]:
np.eye(5)

In [ ]:
np.shape(s)