In [14]:
import numpy as np

s = np.random.randint(1,125,125).reshape(5,5,5)
print(s)

[[[ 79  38  39  94  91]
  [ 12  90  31   8  82]
  [109  89  14 106  80]
  [ 23  80  69  61  14]
  [ 75 122  84  74  69]]

 [[ 28 102  64  26 115]
  [ 93 101  79  29 111]
  [ 83  41  60   7   2]
  [  8  56  13  58 101]
  [ 92  13  39  74 118]]

 [[ 25  15  89  67  69]
  [ 80  67  39 119  33]
  [ 22  36  75 123 123]
  [ 90  43 112  68  59]
  [103  67  23 101  30]]

 [[105  11  80 112  33]
  [ 91  95  56  30  11]
  [117  41  50  68  79]
  [ 67 111   4 116  58]
  [ 73  93  92   5  16]]

 [[ 85  22 123  65  27]
  [ 57  81  92  15  98]
  [ 34  16   9  18   5]
  [ 13  35   1  63  19]
  [ 42   3  49  93  72]]]


In [19]:
a = np.random.randint(0,25,25).reshape(5,5)

np.triu(a)
np.tril(a)

array([[13,  0,  0,  0,  0],
       [20,  1,  0,  0,  0],
       [11, 17, 19,  0,  0],
       [11, 17, 12, 17,  0],
       [ 4,  3,  5, 18, 21]])

In [22]:
M1 = np.random.randint(1,16,16).reshape(4,4)
MT1 = M1.T
comparison = M1 == MT1

if comparison.all() == True:
    print("Value matched")
else:
    print("Not Matched")

Not Matched


In [ ]:
a = np.random.randint(1,4,4).reshape(2,2)
b = np.random.randint(1,6,6).reshape(2,3)
c = a*b
p

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.shape(s)

(10, 10)